# - Try to find the GnuTLS OpenSSL compatibility library
# Once done this will define
#  GNUTLS_OPENSSL_FOUND - system has gnutls-openssl
#  GNUTLS_OPENSSL_INCLUDE_DIR - the gnutls-openssl include directory
#  GNUTLS_OPENSSL_LIBRARIES - The libraries needed to use gnutls-openssl
#  GNUTLS_OPENSSL_DEFINITIONS - Compiler switches required for using gnutls-openssl

FIND_PACKAGE(PkgConfig)
PKG_CHECK_MODULES(PC_GNUTLS_OPENSSL gnutls QUIET)

FIND_PATH(GNUTLS_OPENSSL_INCLUDE_DIR gnutls/openssl.h
   HINTS
   ${PC_GNUTLS_OPENSSL_INCLUDEDIR}
   ${PC_GNUTLS_OPENSSL_INCLUDE_DIRS}
   )

FIND_LIBRARY(GNUTLS_OPENSSL_LIBRARY NAMES gnutls-openssl libgnutls-openssl
   HINTS
   ${PC_GNUTLS_OPENSSL_LIBDIR}
   ${PC_GNUTLS_OPENSSL_LIBRARY_DIRS}
   )

MARK_AS_ADVANCED(GNUTLS_OPENSSL_INCLUDE_DIR GNUTLS_OPENSSL_LIBRARY)

# handle the QUIETLY and REQUIRED arguments and set GNUTLS_OPENSSL_FOUND to
# TRUE if all listed variables are TRUE
INCLUDE(FindPackageHandleStandardArgs)
FIND_PACKAGE_HANDLE_STANDARD_ARGS(GnuTLS_OpenSSL DEFAULT_MSG GNUTLS_OPENSSL_LIBRARY GNUTLS_OPENSSL_INCLUDE_DIR)

IF(GNUTLS_OPENSSL_FOUND)
    SET(GNUTLS_OPENSSL_LIBRARIES ${GNUTLS_OPENSSL_LIBRARY})
    SET(GNUTLS_OPENSSL_INCLUDE_DIRS ${GNUTLS_OPENSSL_INCLUDE_DIR})
    SET(GNUTLS_OPENSSL_DEFINITIONS ${PC_GNUTLS_OPENSSL_CFLAGS_OTHER})
ENDIF()
